FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt /app/
COPY requirements.test.txt /app/

RUN pip install -r requirements.txt
RUN pip install -r requirements.test.txt

COPY src /app/src/
COPY tests /app/tests/
